mkdir -p deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/
mkdir -p deps/stringless_harp/Middlewares/Third_Party/FatFs/src/
mkdir -p deps/stringless_harp/Middlewares/Third_Party/FatFs/src/
set -e; rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d.$$; \
    sed 's,\(stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall\)\.o[ :]*,\1.o deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d : ,g' < deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d.$$ > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d; \
    rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c.d.$$
set -e; rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d.$$; \
    sed 's,\(stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv\)\.o[ :]*,\1.o deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d : ,g' < deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d.$$ > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d; \
    rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c.d.$$
mkdir -p deps/stringless_harp/Middlewares/Third_Party/FatFs/src/
set -e; rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d.$$; \
    sed 's,\(stringless_harp/Middlewares/Third_Party/FatFs/src/ff\)\.o[ :]*,\1.o deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d : ,g' < deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d.$$ > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d; \
    rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d.$$; \
    sed 's,\(stringless_harp/Middlewares/Third_Party/FatFs/src/diskio\)\.o[ :]*,\1.o deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d : ,g' < deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d.$$ > deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d; \
    rm -f deps/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.d.$$
mkdir -p deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p deps/stringless_harp/Core/Src/
set -e; rm -f deps/stringless_harp/Core/Src/syscalls.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Core/Src/syscalls.c > deps/stringless_harp/Core/Src/syscalls.c.d.$$; \
    sed 's,\(stringless_harp/Core/Src/syscalls\)\.o[ :]*,\1.o deps/stringless_harp/Core/Src/syscalls.c.d : ,g' < deps/stringless_harp/Core/Src/syscalls.c.d.$$ > deps/stringless_harp/Core/Src/syscalls.c.d; \
    rm -f deps/stringless_harp/Core/Src/syscalls.c.d.$$
set -e; rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d.$$; \
    sed 's,\(stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal\)\.o[ :]*,\1.o deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d : ,g' < deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d.$$ > deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d; \
    rm -f deps/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.d.$$
mkdir -p deps/stringless_harp/Core/Startup/
set -e; rm -f deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 --std=c++17 -ffast-math -fno-math-errno --exceptions -g stringless_harp/Core/Startup/startup_stm32f469zitx.s > deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d.$$; \
    sed 's,\(stringless_harp/Core/Startup/startup_stm32f469zitx\)\.o[ :]*,\1.o deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d : ,g' < deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d.$$ > deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d; \
    rm -f deps/stringless_harp/Core/Startup/startup_stm32f469zitx.s.d.$$
mkdir -p deps/stringless_harp/FATFS/Target/
mkdir -p deps/stringless_harp/FATFS/App/
set -e; rm -f deps/stringless_harp/FATFS/Target/user_diskio.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/FATFS/Target/user_diskio.c > deps/stringless_harp/FATFS/Target/user_diskio.c.d.$$; \
    sed 's,\(stringless_harp/FATFS/Target/user_diskio\)\.o[ :]*,\1.o deps/stringless_harp/FATFS/Target/user_diskio.c.d : ,g' < deps/stringless_harp/FATFS/Target/user_diskio.c.d.$$ > deps/stringless_harp/FATFS/Target/user_diskio.c.d; \
    rm -f deps/stringless_harp/FATFS/Target/user_diskio.c.d.$$
set -e; rm -f deps/stringless_harp/FATFS/App/fatfs.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g stringless_harp/FATFS/App/fatfs.c > deps/stringless_harp/FATFS/App/fatfs.c.d.$$; \
    sed 's,\(stringless_harp/FATFS/App/fatfs\)\.o[ :]*,\1.o deps/stringless_harp/FATFS/App/fatfs.c.d : ,g' < deps/stringless_harp/FATFS/App/fatfs.c.d.$$ > deps/stringless_harp/FATFS/App/fatfs.c.d; \
    rm -f deps/stringless_harp/FATFS/App/fatfs.c.d.$$
mkdir -p deps/harp_zit6/Src/
mkdir -p deps/harp_zit6/Src/
set -e; rm -f deps/harp_zit6/Src/test_dma_dac.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/test_dma_dac.c > deps/harp_zit6/Src/test_dma_dac.c.d.$$; \
    sed 's,\(harp_zit6/Src/test_dma_dac\)\.o[ :]*,\1.o deps/harp_zit6/Src/test_dma_dac.c.d : ,g' < deps/harp_zit6/Src/test_dma_dac.c.d.$$ > deps/harp_zit6/Src/test_dma_dac.c.d; \
    rm -f deps/harp_zit6/Src/test_dma_dac.c.d.$$
mkdir -p deps/harp_zit6/Src/
mkdir -p deps/harp_zit6/Src/
set -e; rm -f deps/harp_zit6/Src/test_debug_led.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/test_debug_led.c > deps/harp_zit6/Src/test_debug_led.c.d.$$; \
    sed 's,\(harp_zit6/Src/test_debug_led\)\.o[ :]*,\1.o deps/harp_zit6/Src/test_debug_led.c.d : ,g' < deps/harp_zit6/Src/test_debug_led.c.d.$$ > deps/harp_zit6/Src/test_debug_led.c.d; \
    rm -f deps/harp_zit6/Src/test_debug_led.c.d.$$
set -e; rm -f deps/harp_zit6/Src/system_stm32f4xx.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/system_stm32f4xx.c > deps/harp_zit6/Src/system_stm32f4xx.c.d.$$; \
    sed 's,\(harp_zit6/Src/system_stm32f4xx\)\.o[ :]*,\1.o deps/harp_zit6/Src/system_stm32f4xx.c.d : ,g' < deps/harp_zit6/Src/system_stm32f4xx.c.d.$$ > deps/harp_zit6/Src/system_stm32f4xx.c.d; \
    rm -f deps/harp_zit6/Src/system_stm32f4xx.c.d.$$
set -e; rm -f deps/harp_zit6/Src/sysmem.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/sysmem.c > deps/harp_zit6/Src/sysmem.c.d.$$; \
    sed 's,\(harp_zit6/Src/sysmem\)\.o[ :]*,\1.o deps/harp_zit6/Src/sysmem.c.d : ,g' < deps/harp_zit6/Src/sysmem.c.d.$$ > deps/harp_zit6/Src/sysmem.c.d; \
    rm -f deps/harp_zit6/Src/sysmem.c.d.$$
mkdir -p deps/harp_zit6/Src/
mkdir -p deps/harp_zit6/Src/
set -e; rm -f deps/harp_zit6/Src/stm32f4xx_it.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/stm32f4xx_it.c > deps/harp_zit6/Src/stm32f4xx_it.c.d.$$; \
    sed 's,\(harp_zit6/Src/stm32f4xx_it\)\.o[ :]*,\1.o deps/harp_zit6/Src/stm32f4xx_it.c.d : ,g' < deps/harp_zit6/Src/stm32f4xx_it.c.d.$$ > deps/harp_zit6/Src/stm32f4xx_it.c.d; \
    rm -f deps/harp_zit6/Src/stm32f4xx_it.c.d.$$
set -e; rm -f deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/stm32f4xx_hal_msp.c > deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d.$$; \
    sed 's,\(harp_zit6/Src/stm32f4xx_hal_msp\)\.o[ :]*,\1.o deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d : ,g' < deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d.$$ > deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d; \
    rm -f deps/harp_zit6/Src/stm32f4xx_hal_msp.c.d.$$
mkdir -p deps/harp_zit6/Src/
set -e; rm -f deps/harp_zit6/Src/main.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/main.c > deps/harp_zit6/Src/main.c.d.$$; \
    sed 's,\(harp_zit6/Src/main\)\.o[ :]*,\1.o deps/harp_zit6/Src/main.c.d : ,g' < deps/harp_zit6/Src/main.c.d.$$ > deps/harp_zit6/Src/main.c.d; \
    rm -f deps/harp_zit6/Src/main.c.d.$$
mkdir -p deps/harp_zit6/Src/
set -e; rm -f deps/harp_zit6/Src/debug_led.c.d; \
    /opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -MM -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g harp_zit6/Src/debug_led.c > deps/harp_zit6/Src/debug_led.c.d.$$; \
    sed 's,\(harp_zit6/Src/debug_led\)\.o[ :]*,\1.o deps/harp_zit6/Src/debug_led.c.d : ,g' < deps/harp_zit6/Src/debug_led.c.d.$$ > deps/harp_zit6/Src/debug_led.c.d; \
    rm -f deps/harp_zit6/Src/debug_led.c.d.$$
faust -cn faust_dsp_sine -scn faust_dsp_base -fm ../fast_math.hpp -light faust/sine.dsp -o faust/sine.hpp
faust -cn faust_dsp_ks_harp -scn faust_dsp_base -fm ../fast_math.hpp -light faust/ks_harp.dsp -o faust/ks_harp.hpp
mkdir -p obj/harp_zit6/Src/
mkdir -p obj/harp_zit6/Src/
mkdir -p obj/harp_zit6/Src/
mkdir -p obj/harp_zit6/Src/
mkdir -p obj/harp_zit6/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/debug_led.c -o obj/harp_zit6/Src/debug_led.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/main.c -o obj/harp_zit6/Src/main.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/stm32f4xx_hal_msp.c -o obj/harp_zit6/Src/stm32f4xx_hal_msp.o
mkdir -p obj/harp_zit6/Src/
mkdir -p obj/harp_zit6/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/sysmem.c -o obj/harp_zit6/Src/sysmem.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/stm32f4xx_it.c -o obj/harp_zit6/Src/stm32f4xx_it.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/system_stm32f4xx.c -o obj/harp_zit6/Src/system_stm32f4xx.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/test_debug_led.c -o obj/harp_zit6/Src/test_debug_led.o
mkdir -p obj/harp_zit6/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c harp_zit6/Src/test_dma_dac.c -o obj/harp_zit6/Src/test_dma_dac.o
mkdir -p obj/stringless_harp/FATFS/App/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/FATFS/App/fatfs.c -o obj/stringless_harp/FATFS/App/fatfs.o
mkdir -p obj/stringless_harp/FATFS/Target/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/FATFS/Target/user_diskio.c -o obj/stringless_harp/FATFS/Target/user_diskio.o
mkdir -p obj/stringless_harp/Core/Startup/
mkdir -p obj/stringless_harp/Core/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 --std=c++17 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Core/Startup/startup_stm32f469zitx.s -o obj/stringless_harp/Core/Startup/startup_stm32f469zitx.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Core/Src/syscalls.c -o obj/stringless_harp/Core/Src/syscalls.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
mkdir -p obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c -o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o
mkdir -p obj/stringless_harp/Middlewares/Third_Party/FatFs/src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.c -o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.o
mkdir -p obj/stringless_harp/Middlewares/Third_Party/FatFs/src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Middlewares/Third_Party/FatFs/src/ff.c -o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.o
mkdir -p obj/stringless_harp/Middlewares/Third_Party/FatFs/src/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c -o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.o
mkdir -p obj/stringless_harp/Middlewares/Third_Party/FatFs/src/option/
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -DUSE_HAL_DRIVER -DSTM32F469xx -DDSP_CLASS_NAME=sine -I. -Iharp_zit6/Inc -Istringless_harp/Drivers/CMSIS/Include -Istringless_harp/Drivers/CMSIS/Device/ST/STM32F4xx/Include -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc -Istringless_harp/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Istringless_harp/FATFS/App -Istringless_harp/FATFS/Target -Istringless_harp/Middlewares/Third_Party/FatFs/src -lc -lm -lnosys  -Wall -O3 -ffast-math -fno-math-errno --exceptions -g -c stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.c -o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ -specs=nosys.specs -Tstringless_harp/STM32F469ZITX_FLASH.ld -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -mfloat-abi=hard -mlittle-endian -lc -lm -lnosys  -Wl,--gc-sections -flto -Wl,-u_printf_float -o synth.elf obj/harp_zit6/Src/debug_led.o obj/harp_zit6/Src/main.o obj/harp_zit6/Src/stm32f4xx_hal_msp.o obj/harp_zit6/Src/stm32f4xx_it.o obj/harp_zit6/Src/sysmem.o obj/harp_zit6/Src/system_stm32f4xx.o obj/harp_zit6/Src/test_debug_led.o obj/harp_zit6/Src/test_dma_dac.o obj/stringless_harp/FATFS/App/fatfs.o obj/stringless_harp/FATFS/Target/user_diskio.o  obj/stringless_harp/Core/Startup/startup_stm32f469zitx.o obj/stringless_harp/Core/Src/syscalls.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.o obj/stringless_harp/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/diskio.o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/ff.o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/ff_gen_drv.o obj/stringless_harp/Middlewares/Third_Party/FatFs/src/option/syscall.o
/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-size synth.elf
   text	   data	    bss	    dec	    hex	filename
  66116	     68	   3568	  69752	  11078	synth.elf
